### PR TITLE
RFC: #797 Reduce clickable area of CheckboxLabeled

### PR DESCRIPTION
**Pull request by ogupte**
Don't merge, this PR is for just for feedback.

A simple solution is to wrap the existing <label> element so that the label doesn't get stretched to the width of the container. Thoughts?

### CODE REVIEW

**Comment by sodiumjoe** [comment]
if we wanted to go this route, why couldn't we just put `display: flex` on the label.

**Comment by ogupte** [comment]
>if we wanted to go this route, why couldn't we just put display: flex on the label.

That is in fact [how it exists today](https://github.com/appnexus/lucid/blob/master/src/components/CheckboxLabeled/CheckboxLabeled.less#L8)

But it results in the `<label>` being a block element with a full-width click target. My wrapper approach here makes the `<label>` element width the same as the content, which minimizes the click area, but since the wrapper is a block element, it retains its block-level, line-breaking behavior that would otherwise be lost by setting `display: inline-flex` on the `<label>`.

I think there's a different discussion to be had about whether these elements need to be block elements vs inline elements, but the wrapper ensures that it won't break existing layouts.

**Comment by sodiumjoe** [comment]
I see, I guess that's why it makes most sense to me for consuming applications to add the wrapper, as the grouping element. But I'm ok with this too.

**Comment by ogupte** [comment]
>...I guess that's why it makes most sense to me for consuming applications to add the wrapper, as the grouping element...

I agree, but it would have to be something we address in the next major version of the library.

**Pull request closed without merging**
