### PR TITLE
PPR-319 (issue #268): pass all data row props to the <Tr> (semver minor)

### PR DESCRIPTION
**Pull request by chrisdopuch**
## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11 (Win 7)
  - [x] Edge (Win 10)
- [X] Unit tests written (`common` at minimum)
- [X] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- [ ] One core team UX approval

### CODE REVIEW

**Comment by sodiumjoe** [comment]
fixes #268

**Comment by chrisdopuch** [comment]
Talked with @jondlm going to _.pick from row instead of splatting

Also going to add an example file and test manually in browser

**Comment by jondlm** [comment]
Yeah, I was specifically thinking of the case where someone might have data like this: 

```
[
  {foo: 'asdf', children: 'asfd'}
]
```

**Comment by chrisdopuch** [comment]
screen shot 2016-05-19 at 2 13 32 pm

**Comment by chrisdopuch** [comment]
OK tested manually in all browsers, good to merge @jondlm ?

**Pull request merged**
