### PR TITLE
Adds MaximizeIcon

### LINKED ISSUE #380: Maximize Icon
SVG here: https://stash.corp.appnexus.com/projects/CREATIVE/repos/app_creative-ui/browse/src/components/icon/expand-icon.jsx

### PR DESCRIPTION
**Pull request by jonahgeorge**
fixes #380 

## PR Checklist

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] IE11 (Win 7)
  - [x] Edge (Win 10)
- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [x] Two core team engineer approvals
- [x] One core team UX approval

http://docspot.devnxs.net/projects/lucid/380-maximize-icon/#/components/MaximizeIcon

### CODE REVIEW

**Comment by sodiumjoe** [comment]
Can you make a docspot link?

```bash
npm run docs-upload
```

And paste the link here so ux can take a look. Thanks!

**Comment by sodiumjoe** [comment]
the `isBadge` version looks a little funny, and it's not clear to me that we need it?

**Comment by jonahgeorge** [comment]
Docs updated

**Comment by jondlm** [comment]
@jonahgeorge could you merge `master` intro your branch and fix any conflicts so we can merge this one?

**Pull request merged**
