### PR TITLE
refactor: update backuparrowicon, pinicon and props order

### PR DESCRIPTION
**Pull request by lennoxdavidjr**
## PR Checklist

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2164-Update-Icons-SB6-Part-2/?path=/docs/documentation-intro--page)

- Manually tested across supported browsers

  - [x] Chrome
  - [x] Firefox
  - [x] Safari

- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- [ ] One core team UX approval

* PR updates "B" and "C" icons to Storybook 6 compatible format. This includes interactive controls via the UI

### CODE REVIEW

**Review by jhaage — APPROVED** [review]

**Review by dmaloney01 — APPROVED** [review]
UX approved

**Review by dreidn — APPROVED** [review]

**Review by yasskin — CHANGES_REQUESTED** [review]
Looks like the Bell icon dots aren't working. It would be nice to keep the sample stories too, with examples of each color. See the old example:
https://docspot.adnxs.net/projects/lucid/CXP-2164-Update-Icons-SB6/?path=/docs/icons-icons-bellicon-sb5--basic
Clicking on featured color isn't setting the dot currently:
https://docspot.adnxs.net/projects/lucid/CXP-2164-Update-Icons-SB6-Part-2/?path=/docs/icons-icons-bellicon--primary

**Review by yasskin — CHANGES_REQUESTED** [review]
Looks like the CloseIcon colors aren't changing. This Icon is a bit different because the default is a grey not our primary blue. I wonder if it should have the color options at all ? And if Primary for it is grey, not blue...
https://docspot.adnxs.net/projects/lucid/CXP-2164-Update-Icons-SB6-Part-2/?path=/docs/icons-icons-closeicon--primary

**Comment by lennoxdavidjr** [comment]
Very good eye @yasskin If I understand correctly, Close Icon is a special case with special rules governing its color. Looking at the story, it appears that the primary and only color for Close Icon is grey. This icon also has a special feature that changes color slightly when the user hovers over the icon and the `isClickable` prop is set to true and the `isDisabled` prop is set to false. I agree that in this instance that the color feature should be disabled. I will remove that now

**Comment by lennoxdavidjr** [comment]
Additionally, @yasskin I am having no issues changing the bell icon colors or dot colors. I am happy to pair to see if this is an issue

**Pull request merged**
