### PR TITLE
refactor: update icons D & E to SB6

### PR DESCRIPTION
**Pull request by lennoxdavidjr**
## PR Checklist

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2164-Update-Icons-SB6-Part-3/?path=/docs/documentation-intro--page)

- Manually tested across supported browsers

  - [x] Chrome
  - [x] Firefox
  - [x] Safari

- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- [ ] One core team UX approval

* PR updates D, E, & F icons to SB6 format and fixes an issue where the disabled state of the DangerIcon had a blue border

### CODE REVIEW

**Review by tsantef — APPROVED** [review]

**Comment by dmaloney01** [comment]
I'm not seeing the DangerLightIcon (Seen on this overview page: https://docspot.adnxs.net/projects/anx-react/latest/?path=/story/ludic-design-system_documentation-icons-overview--page) Though, I'm not seeing it in the list of available icons in the left column of Storybook. All other icons look good to go.

**Comment by dmaloney01** [comment]
I just noticed the disabled state of the DangerIcon should not have a blue border. This is an issue with the current implementation of the icon. The border should be the same orange as the background color. Let me know if that's outside the scope of this PR and I'll create a bug fix ticket for it.

**Comment by lennoxdavidjr** [comment]
@dmaloney01 Thanks for reviewing! Regarding the DangerLightIcon, there is currently a note in the code that reads: `DEPRECATED: this component should not be used and will be removed from the library in a future release.` As such, I did not include that one in the update. However, it is a very small lift to update and, if you would like, I am happy to do so

**Comment by lennoxdavidjr** [comment]
@dmaloney01 I have gone ahead and updated the disabled state of the DangerIcon so that it no longer has the blue border that you mentioned. I have also updated the storybook link so that you can see it in action. Let me know if you notice any issues

**Comment by dmaloney01** [comment]
Thanks @lennoxdavidjr I'm going to trust that deprecation note, so we can drop the outlined version of the Danger Icon. Thanks for fixing that outline issue as well!

**Review by dmaloney01 — APPROVED** [review]
UX approved

**Pull request merged**
