### PR TITLE
adjust hover colors for SuccessLightIcon and MinusCircleLightIcon

### PR DESCRIPTION
**Pull request by astropunk**
Xandr employees can preview changes [here](https://docspot.adnxs.net/projects/lucid/light-icon-hover/?path=/docs/icons-icons-successlighticon--default)

- Manually tested across supported browsers
  - [x] Chrome
  - [x] Firefox
  - [ ] Safari
  - [ ] Edge (Win 10)
- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [x] Two core team engineer approvals
- [x] One core team UX approval

### CODE REVIEW

**Comment by dsusskind** [comment]
Should it be filled in when isActive? I'm seeing isActive basically behave the same as isClickable in the docspot link

**Comment by astropunk** [comment]
> Should it be filled in when isActive? I'm seeing isActive basically behave the same as isClickable in the docspot link

Hmm, my understanding is that `isActive` should be the same effect as `isClickable` except without the cursor change on hover. @rsadres do you have any input?

**Comment by rsadres** [comment]
I think I agree with Dan. I think isActive should be filled in. The only difference should be the hover color of isClickable as opposed to the hover color of isActive isClickable.
I think.
R

**Comment by astropunk** [comment]
I added a new icon to the example that is clickable and toggles isActive.  Does that feel right to you @rsadres ?

https://docspot.adnxs.net/projects/lucid/light-icon-hover/?path=/docs/icons-icons-successlighticon--default

**Pull request merged**
