### PR TITLE
Converted component sb5 stories to sb6

### PR DESCRIPTION
**Pull request by tsantef**
## PR Checklist

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/mass-migrate-sb5-examples/)

- Manually tested across supported browsers

  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari

- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels
- [ ] Two core team engineer approvals
- [ ] One core team UX approval

### CODE REVIEW

**Comment by yasskin** [comment]
Could you add the docspot URL for Storybook?

**Comment by rcousineau-xandr** [comment]
> Files changed: 400

😅

**Comment by tsantef** [comment]
https://docspot.adnxs.net/projects/lucid/mass-migrate-sb5-examples/

**Comment by yasskin** [comment]
Looks like we're sorting the components into sub-categories now where we used to just organize them by one top level categories
Screen Shot 2021-11-08 at 2 23 00 PM

**Comment by yasskin** [comment]
We're also displaying deprecated components, for instance in the "Helpers" category.
Screen Shot 2021-11-08 at 2 27 50 PM

**Review by yasskin — APPROVED** [review]

**Pull request merged**
