### PR TITLE
[proposal] enforce propType descriptions and allow passing a Generic to `createClass`

### PR DESCRIPTION
**Pull request by jhsu**
benefits:
- `this.props` hints in the render function
- enforce that `propTypes` on the definition has prop-type descriptions

note: tests will break with just this change

Screen Shot 2019-11-19 at 11 01 49 AM

when `propTypes` is missing something from the props interface:
Screen Shot 2019-11-19 at 11 00 23 AM

### CODE REVIEW

**Comment by dsusskind** [comment]
Nice, thanks!

**Comment by jondlm** [comment]
Looks like the compiler isn't happy about some stuff: https://travis-ci.org/appnexus/lucid/jobs/614161934

I can take a look at it later if you don't have the bandwidth.

**Comment by jhsu** [comment]
@jondlm fixed (chromatic still errors)

**Comment by jondlm** [comment]
Awesome, yeah looks like chromatic doesn't like running on forks. I'll merge this.

**Pull request merged**
