### PR TITLE
Feature/ icons

### PR DESCRIPTION
**Pull request by alisonailea**
Reopening for Travis build

### CODE REVIEW

**Comment by alisonailea** [comment]
relates to https://github.com/appnexus/lucid/pull/12

**Comment by jondlm** [comment]
Pushed a few minor fixes. Namely tests for the `Icon` component. Other than that, it looks good to me.

It's been a bit of a journey with this one, but way to stick to it @alisonailea !

Approved.

**Comment by jondlm** [comment]
Just as I say that... It looks like the demo page is broken. I'm looking in to it.

**Comment by jondlm** [comment]
Okay, fixed the documentation issues in 0f0d371

**Comment by ogupte** [comment]
this looks good

**Pull request merged**
